services:
  tjan-scr-rank:
    container_name: tjan-scr-rank
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - USER_NAME
    ports: 
      - "80:80"
    restart: unless-stopped
